language: c
compiler:
- clang
- gcc
script: ruby-install -p https://raw.githubusercontent.com/brixen/ruby_sampling_profiler/master/ruby-$TEST_RUBY_X.$TEST_RUBY_Y/profiler.diff ruby $TEST_RUBY_X.$TEST_RUBY_Y.$TEST_RUBY_Z
matrix:
  include:
  - name: "2.1"
    env:
      - TEST_RUBY_X=2
      - TEST_RUBY_Y=1
      - TEST_RUBY_Z=10
  - name: "2.2"
    env:
      - TEST_RUBY_X=2
      - TEST_RUBY_Y=2
      - TEST_RUBY_Z=10
  - name: "2.3"
    env:
      - TEST_RUBY_X=2
      - TEST_RUBY_Y=3
      - TEST_RUBY_Z=7
  - name: "2.4"
    env:
      - TEST_RUBY_X=2
      - TEST_RUBY_Y=4
      - TEST_RUBY_Z=4
  - name: "2.5"
    env:
      - TEST_RUBY_X=2
      - TEST_RUBY_Y=5
      - TEST_RUBY_Z=1
